### PR TITLE
Usage of vector extension are made better

### LINKED ISSUE #5: Unexpected usage of vector extensions.
**Describe the bug**
When using the vector extensions I expected to use the functions form the static class to change the vector that I'm calling it from.

**To Reproduce**
Make a Vector2 or Vector3:
```cs
Vector3 testVector = new();
```

Call a change function. This will result in a vector that has the value (0, 0, 0)
```cs
testVector.ChangeX(2);
```

Work around:
```cs
testVector = testVector.ChangeX(2);
```

**Expected behavior**
Is that I just call the function and it's already changed. This does apply to all other functions that suggest it changes the vector calling from it.
```cs
Vector3 testVector = new();
testVector.ChangeX(2); // returns (2, 0, 0)
```

**Screenshots**
image
image

**What feature has a bug?**
- Version (0.0.0)
- Scripts that produce the bug: 
- - VectorExtentions.cs

### PR DESCRIPTION
**Pull request by bas-boop**

### CODE REVIEW

File: Assets/Scripts/Extentions/VectorExtensions.cs [hunk 1]
```diff
@@ -160,9 +171,12 @@ public static Vector3 SeparateZ(this Vector3 v, Vector3 f)
         /// <param name="v">This vector3.</param>
         /// <param name="f">The f Vector3.</param>
         /// <returns>A new Vector3 that is multiplied.</returns>
-        public static Vector3 MultipleVector(this Vector3 v, Vector3 f)
+        public static ref Vector3 MultipleVector(ref this Vector3 v, Vector3 f)
```
Comment (BNS-MarkUlrich) [inline Assets/Scripts/Extentions/VectorExtensions.cs]:
```suggestion
        public static ref Vector3 MultiplyVector(ref this Vector3 v, Vector3 f)
```

File: Assets/Scripts/Extentions/VectorExtensions.cs [hunk 2]
```diff
@@ -171,9 +185,10 @@ public static Vector3 MultipleVector(this Vector3 v, Vector3 f)
         /// <param name="v">This Vector3.</param>
         /// <param name="f">The f Vector3.</param>
         /// <returns>A new Vector3 with multiplied X axis.</returns>
-        public static Vector3 MultipleX(this Vector3 v, Vector3 f)
+        public static ref Vector3 MultipleX(ref this Vector3 v, Vector3 f)
```
Comment (BNS-MarkUlrich) [inline Assets/Scripts/Extentions/VectorExtensions.cs]:
```suggestion
        public static ref Vector3 MultiplyX(ref this Vector3 v, Vector3 f)
```

File: Assets/Scripts/Extentions/VectorExtensions.cs [hunk 3]
```diff
@@ -182,9 +197,10 @@ public static Vector3 MultipleX(this Vector3 v, Vector3 f)
         /// <param name="v">This Vector3.</param>
         /// <param name="f">The f Vector3.</param>
         /// <returns>A new Vector3 with multiplied Y axis.</returns>
-        public static Vector3 MultipleY(this Vector3 v, Vector3 f)
+        public static ref Vector3 MultipleY(ref this Vector3 v, Vector3 f)
```
Comment (BNS-MarkUlrich) [inline Assets/Scripts/Extentions/VectorExtensions.cs]:
```suggestion
        public static ref Vector3 MultiplyY(ref this Vector3 v, Vector3 f)
```

File: Assets/Scripts/Extentions/VectorExtensions.cs [hunk 4]
```diff
@@ -193,9 +209,10 @@ public static Vector3 MultipleY(this Vector3 v, Vector3 f)
         /// <param name="v">This Vector3.</param>
         /// <param name="f">The f Vector3.</param>
         /// <returns>A new Vector3 with multiplied Z axis.</returns>
-        public static Vector3 MultipleZ(this Vector3 v, Vector3 f)
+        public static ref Vector3 MultipleZ(ref this Vector3 v, Vector3 f)
```
Comment (BNS-MarkUlrich) [inline Assets/Scripts/Extentions/VectorExtensions.cs]:
```suggestion
        public static ref Vector3 MultiplyZ(ref this Vector3 v, Vector3 f)
```

File: Assets/Scripts/Extentions/VectorExtensions.cs (hunk 1 above)
Comment (BNS-MarkUlrich) [reply Assets/Scripts/Extentions/VectorExtensions.cs]: Also I think it kinda defeats the point to add the "Vector" part to the method name. Since this will already be called directly on Vectors anyway.

File: Assets/Scripts/Extentions/VectorExtensions.cs [hunk 5]
```diff
@@ -309,13 +332,12 @@ public static bool CompareZ(this Vector3 v, Vector3 f, float margin = 0.0001f)
...
+        public static ref Vector3 RandomizeVector(ref this Vector3 v, Vector2 xRange, Vector2 yRange, Vector2 zRange)
         {
-            return new Vector3(
-                Random.Range(xRange.x, xRange.y),
-                Random.Range(yRange.x, yRange.y),
-                Random.Range(zRange.x, zRange.y)
-            );
+            v.x = Random.Range(xRange.x, xRange.y);
+            v.y = Random.Range(yRange.x, yRange.y);
+            v.z = Random.Range(zRange.x, zRange.y);
```
Comment (BNS-MarkUlrich) [inline Assets/Scripts/Extentions/VectorExtensions.cs]: Why doesn't this for example make use of the RandomizeX,Y,Z methods you already made?

File: Assets/Scripts/Extentions/VectorExtensions.cs [hunk 6]
```diff
@@ -514,23 +550,25 @@ public static bool IsZWithinRange(this Vector3 v, Vector3 f, float range)
         #region Change Axis
 
         /// <summary>
-        /// Change the X vector of this Vector2
+        /// Change the X vector of this Vector2 in place.
         /// </summary>
         /// <param name="v">This vector2.</param>
         /// <param name="x">Target value for the X vector.</param>
-        public static Vector2 ChangeX(this Vector2 v, float x)
+        public static ref Vector2 ChangeX(ref this Vector2 v, float x)
```
Comment (BNS-MarkUlrich) [inline Assets/Scripts/Extentions/VectorExtensions.cs]: Why "Change" and not "Set"?

File: Assets/Scripts/Extentions/VectorExtensions.cs [hunk 7]
```diff
@@ -543,9 +581,11 @@ public static Vector2 ChangeY(this Vector2 v, float y)
         /// <param name="v">This vector2.</param>
         /// <param name="f">The f Vector2.</param>
         /// <returns>A new Vector2 that is a combination.</returns>
-        public static Vector2 CombineVector(this Vector2 v, Vector2 f)
+        public static ref Vector2 CombineVector(ref this Vector2 v, Vector2 f)
```
Comment (BNS-MarkUlrich) [inline Assets/Scripts/Extentions/VectorExtensions.cs]: The word combine doesn't always have to mean you're only performing addition. I suggest not overcomplicating the naming and just calling this "Add()"

File: Assets/Scripts/Extentions/VectorExtensions.cs [hunk 8]
```diff
@@ -565,46 +606,51 @@ public static Vector2 CombineX(this Vector2 v, Vector2 f)
...
 
         /// <summary>
         /// Remove the given Vector2 from this Vector2.
         /// </summary>
         /// <param name="v">This vector2.</param>
         /// <param name="f">The f Vector2.</param>
-        /// <returns>A new Vector2 that is a separation.</returns>
-        public static Vector2 SeparateVector(this Vector2 v, Vector2 f)
+        /// <returns>A new Vector2 that is a subtraction.</returns>
+        public static ref Vector2 SubtractVector(ref this Vector2 v, Vector2 f)
```
Comment (BNS-MarkUlrich) [inline Assets/Scripts/Extentions/VectorExtensions.cs]: See? You're doing it here :p

File: Assets/Scripts/Extentions/VectorExtensions.cs [hunk 9]
```diff
@@ -617,9 +663,11 @@ public static Vector2 SeparateY(this Vector2 v, Vector2 f)
         /// <param name="v">This vector2.</param>
         /// <param name="f">The f Vector2.</param>
         /// <returns>A new Vector2 that is multiplied.</returns>
-        public static Vector2 MultipleVector(this Vector2 v, Vector2 f)
+        public static ref Vector2 MultipleVector(ref this Vector2 v, Vector2 f)
```
Comment (BNS-MarkUlrich) [inline Assets/Scripts/Extentions/VectorExtensions.cs]:
```suggestion
        public static ref Vector2 MultiplyVector(ref this Vector2 v, Vector2 f)
```

File: Assets/Scripts/Extentions/VectorExtensions.cs [hunk 10]
```diff
@@ -628,9 +676,10 @@ public static Vector2 MultipleVector(this Vector2 v, Vector2 f)
         /// <param name="v">This Vector2.</param>
         /// <param name="f">The f Vector2.</param>
         /// <returns>A new Vector2 with multiplied X axis.</returns>
-        public static Vector2 MultipleX(this Vector2 v, Vector2 f)
+        public static ref Vector2 MultipleX(ref this Vector2 v, Vector2 f)
```
Comment (BNS-MarkUlrich) [inline Assets/Scripts/Extentions/VectorExtensions.cs]:
```suggestion
        public static ref Vector2 MultiplyX(ref this Vector2 v, Vector2 f)
```

File: Assets/Scripts/Extentions/VectorExtensions.cs [hunk 11]
```diff
@@ -639,9 +688,10 @@ public static Vector2 MultipleX(this Vector2 v, Vector2 f)
         /// <param name="v">This Vector2.</param>
         /// <param name="f">The f Vector2.</param>
         /// <returns>A new Vector2 with multiplied Y axis.</returns>
-        public static Vector2 MultipleY(this Vector2 v, Vector2 f)
+        public static ref Vector2 MultipleY(ref this Vector2 v, Vector2 f)
```
Comment (BNS-MarkUlrich) [inline Assets/Scripts/Extentions/VectorExtensions.cs]:
```suggestion
        public static ref Vector2 MultiplyY(ref this Vector2 v, Vector2 f)
```

**Review by BNS-MarkUlrich — APPROVED** [review]
